### ISSUE TITLE
AssertionError about Vmaf in Windows10

### ISSUE THREAD

**Issue by zzq0516** [Netflix/vmaf#1049]
I used this [https://github.com/Netflix/vmaf/blob/master/resource/doc/windows.md](url) way to bulid projects in windows system,but when i run run_vmaf.py it gave me a error about AssertionError,can you tell me some wrong with this.
![image](https://user-images.githubusercontent.com/61896899/175886859-8b2a6dd2-7f58-4a98-9345-77b015f304f2.png)

**Comment by nilfm** [comment]
Hi,

I don't have access to a Windows system at the moment, but taking a look at the [meson documentation](https://mesonbuild.com/Running-Meson.html#configuring-the-build-directory) and trying it out on my Mac, I have found the following:
1. The following instruction in our [Windows docs](https://github.com/Netflix/vmaf/blob/master/resource/doc/windows.md) seems wrong - the order of the arguments should be `meson setup builddir srcdir`, but we are passing them as `meson setup srcdir builddir`. However, trying it out on my system, Meson is smart enough to understand which one is the srcdir, so I don't think this is causing your problem.
2. The `meson install -C libvmaf/build` is going to install VMAF at the path provided with `--prefix` earlier. The `run_vmaf.py` script expects an installed VMAF at `libvmaf/build/tools/vmaf`. I see two possible fixes:
  a) If you have access to `ninja`, you can run `ninja -vC libvmaf/build`, and that will generate the build files in the right location.
  b) Otherwise, you can create a file in `python/vmaf/externals.py` and specify the path to your VMAF executable like this:
```
VMAFEXEC_PATH = '<path to your executable>'
```

The following commands worked on my system without using ninja:
```
# Here, you can replace /tmp/vmaf with any absolute path you like
meson setup libvmaf/build libvmaf -Denable_float=true --prefix /tmp/vmaf
meson install -C libvmaf/build
# Replace /tmp/vmaf with whatever path you used earlier
echo "VMAFEXEC_PATH = '/tmp/vmaf/bin/vmaf'" > python/vmaf/externals.py
# Run the run_vmaf.py script
PYTHONPATH=python ./python/vmaf/script/run_vmaf.py \           
  yuv420p 576 324 \
  src01_hrc00_576x324.yuv \
  src01_hrc01_576x324.yuv \
  --out-fmt json
```

**Comment by nilfm99** [comment]
Closing as inactive, please reopen if you are still having this issue.
