### ISSUE TITLE
Question: how can I run vmaf on single images ?

### ISSUE THREAD

**Issue by boxerab** [Netflix/vmaf#1168]
Does it make sense to take a single frame image and use vmaf to measure quality ?
I suppose I could generate a video from the frame by duplication. Or is there a better way ?

**Comment by slhck** [comment]
VMAF is composed of [multiple features](https://github.com/Netflix/vmaf/blob/master/resource/doc/features.md#feature-overview) and in principle it also works on single frames. But some metrics like the one comparing motion won't work, and I'd suppose that simply duplicating frames will negatively impact the results, since VMAF was trained on video sequences and not images.

For single images I'd rather stick to the individual metrics (VIF, (MS-)SSIM, …).

(Note: the creators of VMAF might beg to differ; only weighing in as a user.)

**Comment by kylophone** [comment]
FWIW, we have discussed VMAF as an image quality metric (and some alternatives) in this techblog from 2020:

https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4

**Comment by li-zhi** [comment]
You can use VMAF to measure a single-frame image. You need to prepare the input in YUV frame format (or use FFmpeg's filter chaining). When evaluating a single frame, VMAF will set the "motion" feature value to "0", meaning depriving of the motion masking effect from its estimation.

**Comment by slhck** [comment]
Particularly relevant part of that article:

> VMAF, as of today, is a metric trained and developed to judge encoded videos rather than static images. The range of distortions associated with the range of image codecs in our tests is broader than what was considered in the VMAF development process and to that end, it may not be an accurate measure of image quality for those codecs. Further, today’s VMAF model is not designed to capture chroma artifacts and hence would be unable to distinguish between 420 and 444 subsampling, for instance, apart from other chroma artifacts (this is also true of some other measures we’ve used, but given the lack of alternatives, we’ve leaned on the side of using the most well tested and documented image quality metrics). This is not to say that VMAF is grossly inaccurate for image quality, but to say that we would not use it in our evaluation of image compression algorithms with such a wide diversity of codecs at this time.

I also wonder if there's a bias because temporal masking was simply never present in the video training dataset. Any guess as to how much more optimistic VMAF might for images then?

**Comment by christosbampis** [comment]
The video dataset used for training involved different amounts of motion, as measured by the SAD/motion feature, and low values were present therein. Since the number of data points with "motion=0" is not super dense, evaluating still picture quality, and appropriately discounting temporal masking, could be improved.

However, as the article states, VMAF is not "grossly inaccurate" for image quality assessment. As mentioned above, you can apply it using a single-frame input and use it with the above caveats in mind.

**Comment by nilfm** [comment]
I believe this issue was resolved, closing it. Please feel free to re-open if you have further questions.
