### ISSUE TITLE
ffmpeg2vmaf control threading/speed

### ISSUE THREAD

**Issue by nandakd** [Netflix/vmaf#119]
The ffmpeg2vmaf command gives about 5% utilization. Is there an option to increase the number of threads and thus, utilization?

**Comment by li-zhi** [comment]
If you have more than one video sequences to process, you can increase the
cpu utilization by parallelizing the processing over multiple processes.
Search 'parallelize' in README.

**Comment by nandakd** [comment]
Right, my wrapper script is already launching multiple vmaf processes - but I just wanted to understand the level of parallelism within the core vmaf computation.

**Comment by li-zhi** [comment]
Currently the implementation has SIMD for some computationally intensive
feature extraction operations; it doesn't have frame-level parallelism.
However, given the nature of the computation mostly on a per-frame basis
and the structuring of the code, it should be fairly straightforward to
extend it to support frame parallelism.

**Comment by nandakd** [comment]
Thanks, will check that out as well

**Comment by FireCulex** [comment]
@cosmin the problem with ffmpeg's implementation is it doesn't support the 5 percent pool.

**Comment by cosmin** [comment]
@FireCulex what is the 5 percent pool?

**Comment by FireCulex** [comment]
@cosmin ffmpeg2vmaf has an option --pool perc5 that allows you to get the VMAF score of the worst 5% of frames rather then the average of the entire video. I find this more suitable when determining quality as viewers tend to determine quality based on the worst parts of the video instead of it as a whole. 

Its similar to how video card and processors benchmarks list the min average and 1% frametime. The average might be higher for a cpu compared to another but also may have a lower 1% which indicates it has stutter therefore is actually inadequate for the task.

**Comment by cosmin** [comment]
@FireCulex that definitely seems like something that probably should be be added to libvmaf as well. @li-zhi thoughts on adding the `perc` pool methods to libvmaf? I can probably take a stab at a patch for it.

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up as it has been open for a long time and is probably not relevant now. Please feel free to reopen if needed.
