### ISSUE TITLE
enable_transform=true got the same score with enable_transform=false

### ISSUE THREAD

**Issue by RonMX** [Netflix/vmaf#1221]
I'm using ffmpeg 6.0 to caculate the vmaf score of transcode video. But no matter I specify enable_transform=true or false, I always got the same score. Do you know what's the root cause?

cmd 1:
./ffmpeg-6.0-amd64-static/ffmpeg -i 360_video.mp4 -i origin_video.mp4 -filter_complex "[0:v]scale=1920x1080:flags=bicubic[dst];[1:v]scale=1920x1080:flags=bicubic[src];[dst][src]libvmaf=model='enable_transform=true':n_subsample=3:feature='name=psnr':n_threads=16:log_fmt=json:log_path=./tests.vmaf.psnr.log:model='path=./ffmpeg-6.0-amd64-static/model/vmaf_v0.6.1.json'"  -f null -

result1:
frame=  375 fps=188 q=-0.0 Lsize=N/A time=00:00:15.00 bitrate=N/A speed=7.51x
video:176kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_libvmaf_2 @ 0x5b59480] VMAF score: 75.322442

cmd2: 
./ffmpeg-6.0-amd64-static/ffmpeg -i 360_video.mp4 -i origin_video.mp4 -filter_complex "[0:v]scale=1920x1080:flags=bicubic[dst];[1:v]scale=1920x1080:flags=bicubic[src];[dst][src]libvmaf=model='enable_transform=false':n_subsample=3:feature='name=psnr':n_threads=16:log_fmt=json:log_path=./tests.vmaf.psnr.log:model='path=./ffmpeg-6.0-amd64-static/model/vmaf_v0.6.1.json'"  -f null -

result2:
frame=  375 fps=186 q=-0.0 Lsize=N/A time=00:00:15.00 bitrate=N/A speed=7.46x
video:176kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_libvmaf_2 @ 0x5b3cdc0] VMAF score: 75.322442

**Comment by nilfm** [comment]
I believe that by passing `model` in twice, you may be overwriting it instead of keeping both configurations. In your commands you are passing in both `model='enable_transform=true'` and `model='path=./ffmpeg-6.0-amd64-static/model/vmaf_v0.6.1.json'`. You can use `-loglevel debug` on your command to verify that it is being set twice.

I was able to get a different score by passing in a single model like this: `model='path=./ffmpeg-6.0-amd64-static/model/vmaf_v0.6.1.json\\:enable_transform=true'`.

Check out the examples in the documentation [here](https://ffmpeg.org/ffmpeg-filters.html#Examples-91), particularly the one about passing in multiple models, for reference. Please let me know if the updated command still doesn't work for you.

**Comment by RonMX** [comment]
Awsome, that's it. Thank you so much!

**Comment by nilfm** [comment]
No problem, glad it was fixed! Linking #1187 which is a similar issue for reference.
