### ISSUE TITLE
Query using ctypes for Training VMAF

### ISSUE THREAD

**Issue by kanlions** [Netflix/vmaf#1259]
Hi
I am trying to train vmaf for a custom dataset but I still get this  AttributeError: Module 'scipy' has no attribute 'ctypeslib'.
I tried updating libsvm and current version is 3.32.0 and also scipy is 1.11.1.
Is there a work around for this issue for time being I have replaced scipy.ctypeslib with np.ctypeslib.
Is this fix enough or will it lead to other issues
Thanks,

**Comment by nilfm** [comment]
Hi, thanks for the report. I have found [a related thread](https://stackoverflow.com/questions/73320617/attributeerror-when-i-use-libsvm-on-python) (which you may have found as well) saying this is fixed by upgrading `libsvm` to 3.3 or above, but you seem to have done this already.

Could you clarify where or how you have "replaced scipy.ctypeslib with np.ctypeslib"? Do you mean in the library code itself? I can see that [version 3.25](https://github.com/cjlin1/libsvm/blob/v325/python/libsvm/svm.py) contains references to `scipy.ctypeslib` but [version 3.32](https://github.com/cjlin1/libsvm/blob/v332/python/libsvm/svm.py) has replaced them with `np.ctypeslib`. Is it possible that you are still using 3.25 due to an environment issue?

**Comment by kanlions** [comment]
Thank you for your comment. I will try with a fresh virtual environment and check about the issue. I made two changes in the svm.py file mentioned.
I have another question, do you have any trained model integrated with CAMBI for 4K videos. 
Currently we test with vmaf_4k_v0.6.1.json which is trained on default features. We are interested in testing other feature extractors but still the Netflix dataset is copyrighted so is it possible to find other 4K models for testing

**Comment by krasuluk** [comment]
Hi @kanlions, regarding your second question, you may be interested in [this paper](https://arxiv.org/pdf/2202.11038.pdf) from ICIP 2022. It makes a case for making VMAF "banding aware" without retraining by linearly combining it with CAMBI.

**Comment by kanlions** [comment]
Thank you @krasuluk for the resource and I am looking into it. Well CAMBI is one of the features I am interested in. Overall my intention is to look into the feature extraction in the pipeline and check the feasibility of customization. Actually since the underlying data for the vmaf_4k_v0.6.1.json is unknown I am not sure how it works for relatively new technologies like VVENC and I assume such videos may not be part of training. I was wondering if multiple trained models with different underlying features are available to gain more insight.

**Comment by krasuluk** [comment]
@kanlions we currently do not have multiple models with different features trained using the same underlying data as vmaf_4k_v0.6.1. 

Nevertheless, if you are looking into the customization, I think you can use a different training dataset and compare what happens when you use a different feature set. After all, as mentioned for example [here](https://www.thevideoverse.co/1984843/13313674), the training is not the main driver of the model's performance -- in the video, Zhi mentions roughly 30% of accuracy coming from the training part. That means you should be able to get a reasonable idea about the behavior when you add different features even if you train your models on your custom data.

**Comment by nilfm99** [comment]
Closing this thread as it's been inactive for a while, and it has deviated from the original issue. If you'd like to ask further about a new topic, please open a new issue for it.
