### ISSUE TITLE
Issue with Third party feature extraction

### ISSUE THREAD

**Issue by kanlions** [Netflix/vmaf#1275]
I was attempting to use the STTRED feature by running as given in the Git instructions as below
matlab -nodisplay -nosplash -nodesktop -r "run_strred('../../python/test/resource/yuv/src01_hrc00_576x324.yuv', '../../python/test/resource/yuv/src01_hrc01_576x324.yuv', 576, 324); exit;"

But I find 1200 frames in STRRED as compared to 600 frames in the VMAF for same set of videos. What is the correct way of running STRRED ? 
I can share test outputs if required?

**Comment by krasuluk** [comment]
Hi @kanlions, can you please share the outputs? I was under the impression that the src01_hrc00_576x324.yuv file should only have 48 frames...

**Comment by kanlions** [comment]
[strred.txt](https://github.com/Netflix/vmaf/files/13525713/strred.txt)
[vmaf.txt](https://github.com/Netflix/vmaf/files/13525716/vmaf.txt)

Apologies for confusion. I had run on a custom video. I am sharing the vmaf and strred generated from this github for the same reference-target pair, I am having difficulty in understanding how twice number of frames are coming for STRRED in comparison to VMAF.

**Comment by kanlions** [comment]
Thanks for your reply. Yes the bit depth is indeed 10 bit. I will try changing to 8bit and rerun and see what happens

**Comment by nilfm** [comment]
Great, please let me know if that didn't work.

**Comment by kanlions** [comment]
@nilfm Thanks for all the support the 8 bit version works fine. But now I have run into challenges https://github.com/Netflix/vmaf/blob/master/python/vmaf/core/matlab_quality_runner.py it may be due to environment clash  but I couldnot find any test case for matlab_quality_runner in the test folder. Was there any test case for these features?

**Comment by nilfm** [comment]
@kanlions I believe you're looking for this: https://github.com/Netflix/vmaf/blob/e698b4d788fb3dcabdc4df2fd1bffe88dc0d3ecd/python/test/extra/feature_extractor_extratest.py#L25-L44

This is not present in master because it was removed 1.5 years ago in [this commit](https://github.com/Netflix/vmaf/commit/c69c3adc46a6b8c56298390ffb6779ece010a6d0), @li-zhi do you know why those tests were removed? Note that they are mentioned in `CONTRIBUTING.md` [here](https://github.com/Netflix/vmaf/blob/master/CONTRIBUTING.md?plain=1#L96-L125).

Hopefully that test helps you understand how to call the quality runner. I believe you can use your original 10b file and add `"workfile_yuv_type": "yuv420p"` to `asset_dict` to have an automatic conversion but I'm not sure the Matlab-related components are set up correctly for that.
