### ISSUE TITLE
version mismatch between build version for libvmaf and the python code

### ISSUE THREAD

**Issue by SingingBush** [Netflix/vmaf#1309]
as mentioned in #1307, the version for the meson build is defined in `libvmaf/meson.build` and the version for the python library comes from `python/vmaf/__init__.py`. This means it's likely for them to get out of sync, which is currently the case in master.

**Comment by jacoblubecki** [comment]
I'm open to taking a stab at this, but I wanted to also double check that it makes sense -- does the release process guarantee that the python code will reflect support for the co-bundled libvmaf code version? I could imagine a scenario where the libvmaf version gets released first and then the python bindings are updated later to match.

**Comment by nilfm99** [comment]
I think we are never going to intentionally release in such a way that the python wrapper is incompatible with the bundled libvmaf version. If we deprecate an API, we won't remove it immediately and there will be a transition period in which the python wrapper can be updated before it is removed. So if the python version number is made to automatically track the libvmaf one, that seems correct to me.

pinging @kylophone to verify this

**Comment by nilfm99** [comment]
We have discussed this and we think decoupling the C and python versions makes the most sense so they can progress separately without needing to bump one of them for changes to the other. Currently they are still the same but they may/will diverge. Closing this thread since there is no need for the synchronization anymore. Thanks for raising this issue.
