### ISSUE TITLE
How to compute DMOS?

### ISSUE THREAD

**Issue by liuxj901103** [Netflix/vmaf#205]
Hi,I want to creat my own data set. But I don't know how to compute DMOS.More  detailed,I want to know how to normalized my score to  the range 0 to 100 from the range 1 to 5?

**Comment by slhck** [comment]
You can convert from 1–5 to 0–100 linearly: `y = 100*((x-1)/4)` where `x` is your original score.

However, the meaning of DMOS depends on your original test. Did your test include hidden reference videos (e.g., ACR-HR method)? Or did you just show different degraded videos without a reference?

**Comment by liuxj901103** [comment]
Thank you for your reply. I noticed such a description in the file vmaf/resource/doc/models.md, that is "The raw subjective scores collected are then cleaned up using the MLE methodology, as described in [SUREAL](https://github.com/Netflix/sureal). The aggregate subjective scores after clean-up are mapped to a score in the VMAF score, where "bad" is mapped to roughly score 20, and "excellent" to 100." Can you explain it for me.

**Comment by slhck** [comment]
Ah, I hadn't seen that – if VMAF originally has not been mapped to subjective scores such that 0 corresponds to the absolute worst rating, that leaves some "negative headroom" for lower scores. As to why that was being done, I can only guess, as it is not strictly necessary. Perhaps one of the developers can weigh in.

**Comment by liuxj901103** [comment]
Got it. Thanks.

**Comment by li-zhi** [comment]
@slhck @liuxj901103 The reason why we map 1 (bad) to 20 instead of 0 is to hope to leverage the extrapolation power of the predictor to cover wider range of quality at the low end.

In fact, if you are training a new model, the mapping into [0, 100] is not strictly necessary. The predicted score will just stay in its original scale of 1-5. You can further disable the 'clipping' in the training parameter file so that the score can go beyond [1, 5] (search `score_clip` in https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md).

**Comment by slhck** [comment]
Thanks for your explanation! However, would the same logic not apply to the upper end of the scale as well? Thinking about subjective tests we've conducted, and also some requirements from industry vendors that we hear often, we'd always notice that:

1. what constitutes a "bad" clip does not really change for subjects, if you include sufficiently low quality stimuli in the test, and
2. that vendors are more interested in minor variations at high quality (e.g. encoder shootouts), since they know that if the score is lower than, say, 50, you're pretty much annoying users already

**Comment by ciwei123** [comment]
@slhck @li-zhi @liuxj901103 Hi， Could you tell me the difference of “MOS” 、“OS” and "DMOS"？I think their relationship is as follows：
MOS = mean of OS
DMOS = MOS of reference video  -  MOS of distoration distorted video ？
And could you share the method or scripts that covert the "os " to the "DMOS"？ 
Thank you very much!!!!

**Comment by slhck** [comment]
I would generally not use the term "OS" but rather refer to it as (individual, subjective) ratings. The "O" might stand for opinion, but people also sometimes use it for "objective", so it's a big ambiguous.

Using DMOS is only valid if your subjects rated an reference video. In that case, you need to take the score the user gave to the reference video and, from that, subtract the score that the viewer gave for the distorted video. Then you can average the differential scores to get a DMOS. The only standardized definition of DMOS is described in ITU-T Rec. P.910, Section 6.2 (Absolute category rating with hidden reference (ACR-HR)). Here, the DMOS is the average of the individual differential ratings.

**Comment by slhck** [comment]
PS: There are no generally applicable scripts or functions since there is no common data format for subjective test results. However, it's a rather straightforward calculation.

**Comment by ciwei123** [comment]
@slhck Thanks for your reply.  I got it right,and I understand the means of DMOS.  But ,I find that vmaf score and DMOS are positive correlation.   However,the fact is that higher vamf score means better video's quality,  the lower DMOS means better video's quality.The fact is contradiction with the VMAF PROJECT.

**Comment by ciwei123** [comment]
@slhck vmaf/resource/example/example_dataset.py:

dis_videos = [ {'content_id': 0, 'asset_id': 0, 'dmos': 100, 'path': VmafConfig.test_resource_path('yuv', 'checkerboard_1920_1080_10_3_0_0.yuv')}, # ref {'content_id': 0, 'asset_id': 1, 'dmos': 50, 'path': VmafConfig.test_resource_path('yuv', 'checkerboard_1920_1080_10_3_1_0.yuv')}, {'content_id': 1, 'asset_id': 2, 'dmos': 100, 'path': VmafConfig.test_resource_path('yuv', 'flat_1920_1080_0.yuv')}, # ref {'content_id': 1, 'asset_id': 3, 'dmos': 80, 'path': VmafConfig.test_resource_path('yuv', 'flat_1920_1080_10.yuv')},]


From the script,we can find that the ref video's DMOS(the best quality) is 100,  but by the definition of DMOS,DMOS should be 0.

**Comment by slhck** [comment]
Sorry, I was a bit mistaken. Please read the section in P.910.

It says:

> Differential viewer scores (DV) are calculated on a per subject per processed video sequence (PVS) basis. The appropriate hidden reference (REF) is used to calculate DV using the following formula:

> DV(PVS) = V(PVS) – V(REF) + 5

So, higher scores are better.

**Comment by ciwei123** [comment]
@slhck I think the DMOS= 100-MOS(PVS),and higher DMOS are worse.
For example，LIVE database、CSIQ database、and TID database all give the DMOS，and the three databases all prove that and higher DMOS are worse.

**Comment by slhck** [comment]
It actually never occurred to me that there was a difference in interpretation, given that the only standardized description of DMOS is in P.910. (That said, the description actually lacks a formula of how to compute the DMOS as the mean of DV, and it does not allow for other scales than the ACR scale, since it's part of the ACR-HR method, but …)
It is probably the fault of the authors of the respective databases that they did not use the standardized definition of DMOS. But to summarize it means that the usage within VMAF is correct; VMAF predicts DMOS on a 0–100 scale.

**Comment by ciwei123** [comment]
@slhck Thanks for your reply. Could you tell me the way by which  "example_raw_dataset.py" can be change into "example_dataset.py" ，"NFLX_dataset_public_raw.py"  to "NFLX_dataset_public.py"? I use the function "def test_generate_dataset_from_raw_default(self):" in routine_test.py  to deal with "NFLX_dataset_public_raw.py",but I get a different "NFLX_dataset_public.py" , and I get the key "groundtruth" not the "DMOS".    Thank you very much!!!

**Comment by li-zhi** [comment]
@ciwei123 I believe what you are looking for sits in another repo called SUREAL (which VMAF depeonds on), and the method to invoke what you wanted is this one:
https://github.com/Netflix/sureal/blob/0a07805ff91f6e0a567387ce3a63b19005475090/sureal/subjective_model.py#L76

Feel free to dig into it. If you encounter any issues, let me know.

**Comment by ciwei123** [comment]
@li-zhi Thanks for your reply. From the script "SUREAL/subjective_model.py", I can understand that DMOS = MOS + ref_score (e.g. 5.0) - MOS_of_ref_video.
And I can get the same VQEGHD3_dataset.py provided by the VMAF project. But about the NFLX_dataset_public_raw.py, I get the dmos on a 0–5 scale，but the NFLX_dataset_public.py provided by the VMAF project on a 0-100 scale. Could you tell me the method covert "dmos on a 0–5 scale" to  "dmos on a 0-100 scale"？ Thank you very much.

**Comment by ciwei123** [comment]
@li-zhi  Thanks for your reply. I may be understand the covertion method, NFLX_dataset_public.py is from NFLX_dataset_public_raw_last4outliers.py(not NFLX_dataset_public_raw.py), and from 1–5 to 0–100 linearly: y = 100*((x-1)/4).
Another question, where can I find the detailed explanation of the VIF、adm、motion? And , I have a distortion video with randomly dropped frames，I know that VMAF requires strict frame alignment，how can I test my video by VMAF ? Thank you very much .
