### ISSUE TITLE
VMAF score for "good" quality

### ISSUE THREAD

**Issue by RonLu** [Netflix/vmaf#220]
Hi,

In phone model, when we use VMAF to evaluate the quality of transcoded videos, if the original video is 1080p, what score is seen as "good" quality for different downscaled resolutions like 144, 240, 288, 360, 480, 720, and 1080? 

For example, for 144, score of 1 is seen as good? And for 720, score of 85 is seen as good?

Could you give the recommendation? Thanks a lot!

**Comment by slhck** [comment]
You cannot ignore the quality degradation due to downscaling, so you should not interpret a low score as “good”. If VMAF gives you a score of 1, it *will* be bad for the viewer. In order to find out what the best possible quality is you can achieve for a given resolution, you need to run multiple encodings at different target rates or target quality settings, and find the point at which the quality (according to VMAF) does not improve anymore when you increase the rate. The location of this point will entirely depend on the content though.
