### ISSUE TITLE
Why only consider the Y component and skip the U and V components?

### ISSUE THREAD

**Issue by common1994** [Netflix/vmaf#224]
In the callback function "read_frame", I see that one frame in the original video and the corrupted video is saved with the parameters 'ref_data' and 'dis_data', and then the U and V components are skipped. Is the U and V components not considered in the video reference evaluation, and why?

Below is the general flow of the function 'read_frame'：

int read_frame(float *ref_data, float *dis_data, float *temp_data, int stride_byte, void *s)
{
// some code

// read ref y
// read dis y
**
// ref skip u and v
// dis skip u and v
**

// other code
}

**Comment by common1994** [comment]
@li-zhi 
Can you tell me why this is? Thank you!

**Comment by yuhjay** [comment]
1. VMAF is built upon other metrics, like VIF, ADM and others. These metrics are mainly designed for detecting degradation of luma component. 
2. Why it still works? I think for most encoders, the rate control of UV is solely based on Y so it works.

**Comment by common1994** [comment]
Thank you for your reply. @yuhjay 
I can understand the first point, but I can't understand "the rate control of UV is solely based on Y". I am new to vmaf, and I am a Chinese, can you say something simpler and more detailed?

**Comment by yuhjay** [comment]
I mean the decision of Chroma QP is usually based on Luma. You can check the rate control mechanism of x264 to see how it works.

**Comment by mht13** [comment]
> On Sep 10, 2018, at 3:17 PM, Joe Yuchieh Lin <notifications@github.com> wrote:
> 
> 1. VMAF is built upon other metrics, like VIF, ADM and others. These metrics are mainly designed for detecting degradation of luma component. 
> 2. Why it still works? I think for most encoders, the rate control of UV is solely based on Y so it works.

Awesome response. Technical and to the point. And sent from a mobile. What else can one argue?



> 
> Sent from my iPhone
>

**Comment by christosbampis** [comment]
Your observation is on point: VMAF is currently trained on features extracted only from the luminance component. The previous answers are correct, I would also add that for perceptual quality, the chroma channels are usually not considered. There are algorithms that do look into that (e.g. for color image quality assessment). Indirectly, Y has a larger weight on green, so you can get something from there. Generally speaking, you may not get very large performance improvements from adding in color information (TID13 for image quality is a good counterexample).

Nevertheless, there is a pull request for adding color to VMAF. We have not merged it yet, because we are still thinking on better ways of adding color information and planning more carefully how to add this in. So stay tuned :)

**Comment by common1994** [comment]
Thand you for you reply! @christosbampis 
Although I don't know which attributes of the image affect the perceived quality, I will understand the content related to it. Now I will choose vmaf as the algorithm for our video quality assessment system.

**Comment by ShortyCM** [comment]
Comparing x264/x265 to NVENC highlights how important it is to look at UV in addition to Y.  Using some x264/x265 videos made with various CRF (say, 18-21 range) settings and trying to get similar filesizes/bitrates from NVENC's CQ mode shows how poor NVENC really is, yet somehow scores higher on VMAF than x264/x265 will.  NVENC has horrible blockiness, really a huge mess, in the colour channels.  Yet, it can score higher on VMAF than the x264/x265 encodes despite looking absolutely horrible.  This is especially obvious in darker scenes, where to say NVENC struggles is an understatement.

**Comment by christosbampis** [comment]
Introducing color information is indeed a good thing to do. When looking at the NVENC encodes, did you visually inspect at the color channels separately or combine them with luma?
