### ISSUE TITLE
Provide CMakeLists

### ISSUE THREAD

**Issue by EwoutH** [Netflix/vmaf#311]
For building & compiling with different compilers a CMakeLists.txt would be very useful.

**Comment by 1480c1** [comment]
@EwoutH if you still want a CMakeLists, I have one https://github.com/1480c1/vmaf/tree/cmake (Available as a patch https://github.com/Netflix/vmaf/compare/master...1480c1:cmake.patch) that I will probably keep out-of-source since there's already a meson build system and I wrote the CMakeLists for a certain reason.

I do not recommend checking out that branch as I will probably force-push that often to test if it works on the master branch instead. It would be better if you downloaded it as a patch whenever you update vmaf to the current master branch

```bash
git clone https://github.com/Netflix/vmaf.git
cd vmaf
wget https://github.com/Netflix/vmaf/compare/master...1480c1:cmake.patch
git apply master...1480c1:cmake.patch
mkdir build
cd build
cmake ..

...

git reset --hard origin/master
wget ...
```

**Comment by BoLiu86** [comment]
In windows 10, the follow error occurs when cmake configure state.
CMake Error at CMakeLists.txt:113 (target_link_libraries):
  Object library target "ptools" may not link to anything.

**Comment by 1480c1** [comment]
Will take a look at it later

**Comment by 1480c1** [comment]
@BoLiu86 can you try again?

**Comment by BoLiu86** [comment]
> @BoLiu86 can you try again?

I have try to configure pthread again in Win 10, but it still does not work.

**Comment by 1480c1** [comment]
> > @BoLiu86 can you try again?
> 
> I have try to configure pthread again in Win 10, but it still does not work.

What error?

**Comment by BoLiu86** [comment]
> > > @BoLiu86 can you try again?
> > 
> > 
> > I have try to configure pthread again in Win 10, but it still does not work.
> 
> What error?
Cmake output error information is as follows:
    CMake Error at CMakeLists.txt:113 (target_link_libraries):
    Object library target "ptools" may not link to anything.

**Comment by 1480c1** [comment]
Did you update?

**Comment by BoLiu86** [comment]
> Did you update?

Yes. 
I think it is pthread configure problem in Windows system, but I can not configure it correctly. Do you have some tips?

**Comment by 1480c1** [comment]
I know for msvc it will not work because of thread, but you can first clone the repo, the do
```powershell
Invoke-WebRequest "https://github.com/Netflix/vmaf/compare/master...1480c1:cmake.patch" | git apply
```
in PowerShell in the same folder after making sure to reset the folder (remove the CMakeLists.txt)

**Comment by nilfm** [comment]
Closing this issue as part of a clean-up as it has been open for a long time and is probably not relevant now. Please feel free to reopen if needed.
