### ISSUE TITLE
Incorrect statement in conf_interval.md?

### ISSUE THREAD

**Issue by HolyWu** [Netflix/vmaf#316]
In https://github.com/Netflix/vmaf/blob/master/resource/doc/conf_interval.md#run-in-command-line it says:
> `BOOTSTRAP_VMAF_score` is the final prediction result and is identical to VMAF_score when the --ci option is not used.

But the VMAF score is actually different between CI and non-CI model.

```
$ ./vmafossexec yuv420p 576 324 src01_hrc00_576x324.yuv src01_hrc01_576x324.yuv model/vmaf_v0.6.1.pkl
Start calculating VMAF score...
Exec FPS: 101.796043
VMAF score = 76.699271

$ ./vmafossexec yuv420p 576 324 src01_hrc00_576x324.yuv src01_hrc01_576x324.yuv model/vmaf_rb_v0.6.2/vmaf_rb_v0.6.2.pkl --ci
Start calculating VMAF score...
Exec FPS: 92.460145
VMAF score = 75.443048
```

**Comment by christosbampis** [comment]
The statement is true when you are looking at the same VMAF version (e.g. v0.6.3 with and without --ci). Between v0.6.1 and v0.6.2, there is a change in the underlying environment used to train VMAF, leading to this difference in the reported scores of the full model. In principle, the presence of bootstrapping does not affect the scores, since the full VMAF model is used to report VMAF score. To alleviate for the discrepancy between versions, we have now adopted a containerized approach to train upcoming VMAF versions.

To convince yourself, you could try versions 0.6.1 and 0.6.2 without bootstrapping.

**Comment by HolyWu** [comment]
There is no non-bootstrapping model for v0.6.2 or v0.6.3, and using bootstrapping model without `--ci` yields an error:
```
$ ./vmafossexec yuv420p 576 324 src01_hrc00_576x324.yuv src01_hrc01_576x324.yuv model/vmaf_rb_v0.6.2/vmaf_rb_v0.6.2.pkl
Start calculating VMAF score...
Expect model type LIBSVMNUSVR, but got 'RESIDUEBOOTSTRAP_LIBSVMNUSVR'
Caught VmafException: Incompatible model_type
```
Nevertheless, I see where the difference comes. Thanks for the clarification.

**Comment by christosbampis** [comment]
Sorry, maybe my previous statement was confusing. If you use the vmaf_rb_v0.6.2.pkl file without --ci, the models are indeed incompatible and hence the error. What I originally meant is to look at the VMAF score generated by v0.6.1 (without --ci) and v0.6.2 (with bootstrapping) and v0.6.3 (with bootstrapping). The last two should be identical, while the first one will be different as you noticed.

Maybe it is actually a good idea to think how to avoid confusion for the new versions and the --ci flag.
