### ISSUE TITLE
How to do when frame pts is not same?

### ISSUE THREAD

**Issue by baiyufei** [Netflix/vmaf#317]
I use ffmpeg to produce distorted video from the reference video. The frame PTS of the distorted video and the reference video are different, and the score calculated by ffmpeg libvmaf filter is lower.

Adding an offset to the start time of distorted video will get a higher score like this:
ffmpeg **-ss 0.04** -i main.mp4-i ref.mp4-filter_complex \
";[0:v][1:v]libvmaf" -f null -

Is there a best practice for solving this problem?

Thanks!

**Comment by li-zhi** [comment]
VMAF requires the frames of the reference/distorted videos to be exactly aligned. As far as I know, `-ss` is not frame accurate. I would recommend using the `select` filter of FFmpeg. Googling it the following threads may be helpful:
https://stackoverflow.com/questions/38253406/extract-list-of-specific-frames-using-ffmpeg
https://superuser.com/questions/866144/cutting-videos-at-exact-frames-with-ffmpeg-select-filter

**Comment by slhck** [comment]
If the PTS of the original video are misaligned, there's not much that can be done (other than shifting the PTS). This kind of temporal registration is not easy to do automatically, and ffmpeg can't do it for you, so you have to experiment to find the correct offset.

Note that `-ss` is always frame-accurate in terms of selecting the proper starting point from which a video is read (when used as an option before `-i`) or seeked to (when used after `-i`). However, since `-ss` only works on timestamps and not frame numbers, you you can't really specify a seek offset in number of frames.

You *can* trim off some frames using the `select` filter, e.g., to output only after frame 50:

```
ffmpeg -i main.mp4 -i ref.mp4 \
-filter_complex "[0:v]select=gt(n\,50),setpts=PTS-STARTPTS[v0];[v0][1:v]libvmaf" \
-f null -
```

The `setpts=PTS-STARTPTS` is needed to shift the output PTS. Otherwise, the video would still be out of sync.

Or, the same with the `trim` filter:

```
ffmpeg -i main.mp4 -i ref.mp4 \
-filter_complex "[0:v]trim=start_frame=50,setpts=PTS-STARTPTS[v0];[v0][1:v]libvmaf" \
-f null -
```

The above would start feeding to the output from the 50th frame onward.

**Comment by baiyufei** [comment]
These are very helpful, thank you!
