### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by ROYduan** [Netflix/vmaf#319]
enviroment: 
  Linux version 3.10.107-1-tlinux2-0046
  gcc version 4.8.2

command:
./vmafossexec yuv420p 640 480 niklas_640_480_30_f471_rec.yuv  ../yuv_files/niklas_640_480_30_f471.yuv  ../modle/vmaf_v0.6.1.pkl

phenomenal:
Start calculating VMAF score...
Caught runtime_error: StatVector size is 0.

**Comment by christosbampis** [comment]
Hi, are you able to run the example: 

./wrapper/vmafossexec yuv420p 576 324 python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv model/vmaf_v0.6.1.pkl

The runtime error for invalid sizes is usually due to wrong YUV frame numbers between reference and distorted. Can you please check that the input YUV files have the same resolution and frame number?

**Comment by ROYduan** [comment]
yes, i have checked the YUV files, even i use an same YUV file like:
 ./vmafossexec yuv420p 640 480 niklas_640_480_30_f471_rec.yuv   niklas_640_480_30_f471_rec.yuv ../modle/vmaf_v0.6.1.pkl,  
 runtime error goes still!

**Comment by christosbampis** [comment]
Have you tried the example vmafossexec call I sent above? This seems to be a weird error, so I think it has to do with the input yuv files somehow. You can also share the yuv file with me (if that is possible) to try them myself. Also, are you using master branch, latest commit?

**Comment by ROYduan** [comment]
problem has been solved by change the marco #define MAX_NUM_THREADS  128  to  #define MAX_NUM_THREADS  256  in file  "vmaf/feature/src/common/blur_array.h"
