### ISSUE TITLE
Does VQM-VFD integrated in the vmaf score?

### ISSUE THREAD

**Issue by lazybing** [Netflix/vmaf#343]
I read the tech blog [toward-a-practical-perceptual-video-quality-metric](https://medium.com/netflix-techblog/toward-a-practical-perceptual-video-quality-metric-653f208b9652). 

>  Since VQM-VFD demonstrates good correlation across the four datasets, we are experimenting with VQM-VFD as an elementary metric for VMAF; although it is not part of the open source release VMAF 0.3.1, it may be integrated in subsequent releases.

do the vqm-vfd integrated int the vmaf now?

when I test the basketbal scene vmaf score using different resolution, such 270p and 1080p, when i set the crf value to 18 for 270p and set the crf value to 40 for 1080p content. they both get the 70 vmaf score. but the 270p content looks better than 1080p content. 

If vqm-vfd metric has integrated into the vmaf score, how can i use it?

**Comment by slhck** [comment]
> do the vqm-vfd integrated int the vmaf now?

No, it's not part of VMAF. You can see the implemented features here: https://github.com/Netflix/vmaf/tree/master/feature/src

> when I test the basketbal scene vmaf score using different resolution, such 270p and 1080p, when i set the crf value to 18 for 270p and set the crf value to 40 for 1080p content. they both get the 70 vmaf score. but the 270p content looks better than 1080p content.

What you may be seeing is a bias towards prefering higher resolutions over coding distortions. That could be due to the way VMAF was initially trained; perhaps the used sequences did not include such heavy distortions as you'd expect with CRF 40.

**Comment by lazybing** [comment]
hi slhck,
Thanks.
