### ISSUE TITLE
Do reference video and distorted video need to have the same pixel format? If not, which pixel format should be used when running the vmaf script? 

### ISSUE THREAD

**Issue by willfinnegan** [Netflix/vmaf#48]

**Comment by li-zhi** [comment]
@willfinnegan yes they need to be the same pixel format. You can easily convert between formats using ffmpeg.

**Comment by willfinnegan** [comment]
My reference is yuv422p10le and my distorted video is yuv420p. I was considering converting the source file to yuv420p but the codec for that file (prores) doesn't seem to support that format. Is there some way to get around this issue without transcoding the reference file from prores to h264?

**Comment by li-zhi** [comment]
Shouldn't ffmpeg automatically recognize prores and find the decoder? I found some discussion on ffmpeg producing prores output at:
https://trac.ffmpeg.org/wiki/Encode/VFX
But should ffmpeg taking prores input be straightforward?

**Comment by willfinnegan** [comment]
Sorry my comment was worded poorly. 

My source file is prores (yuv422p10le). My distorted file is h264 (yuv420p). I figured that the prores source file would be the better one to convert because going from yuv422p10le to yuv420p seems like a logical progression. However, when I went to convert my prores file to yuv420p using the  ffmpeg command '-pix_fmt yuv420p', the output file remained yuv422p10le. It seems that the prores codec itself does not support the pixel format yuv420p (I may be wrong about that but ffmpeg would not allow for it). 

So I'm unsure how to proceed. If I try to convert my prores source to yuv420p, it appears that I would have to change the codec as well to a codec that supports that color space and that's not going to give me accurate results. Should I 'upsample' the color space of my distorted video to yuv422p10le? 

Thanks for your help!

**Comment by li-zhi** [comment]
It shouldn't be prores' responsibility to support yuv420p, but ffmpeg's. Can you show me the ffmpeg command line you were using?

**Comment by haiqianw** [comment]
Please try this command
`ffmpeg -i ref.mov -f rawvideo -pix_fmt yuv420p -sws_flags lanczos+accurate_rnd  out.yuv`

**Comment by willfinnegan** [comment]
Thank you, I will try that command now. For reference I was runnning 'ffmpeg -i input.mov -pix_fmt yuv420p -acodec copy -vcodec prores -profile:v 3 output.mov'

**Comment by willfinnegan** [comment]
I did try using the command: `ffmpeg -i ref.mov -f rawvideo -pix_fmt yuv420p -sws_flags lanczos+accurate_rnd out.yuv` 

Using that file as my source, I got these results when running VMAF: 
`    "aggregate": {
        "VMAF_feature_adm2_score": 0.41968884603064227, 
        "VMAF_feature_motion_score": 2.8595670480427042, 
        "VMAF_feature_vif_scale0_score": 0.022593293860438287, 
        "VMAF_feature_vif_scale1_score": 0.079894770119001618, 
        "VMAF_feature_vif_scale2_score": 0.09528996923795105, 
        "VMAF_feature_vif_scale3_score": 0.10540918425853875, 
        "VMAF_score": 1.4885427760404453, 
        "method": "mean"
    }`

**Comment by li-zhi** [comment]
@willfinnegan These numbers doesn't seem to be correct. Very likely the yuv420p files are misaligned. Have you looked at the size of the files to see if they match? Also, try using players like vooya to play the YUV files.

**Comment by haiqianw** [comment]
@willfinnegan If the distorted videos were converted from yuv422p10le to yuv420p with other subsampling method, there may be some problems. Because the new yuv420p source may not be the "real source" of those encodes. `-sws_flags lanczos+accurate_rnd` was specified here.

One can verify this issue by encoding the new source with the same recipe and compare them with your current encodes

**Comment by willfinnegan** [comment]
@haiqianw I think that may be the case. I am going to re-encode the distorted videos from the new yuv420p source and then run again. Thanks

**Comment by willfinnegan** [comment]
I have an update on this: 

I used @haiqianw command to create a rawvideo yuv420p source. However, when attempting to create a set of distorted videos from this source using FFMPEG, I received the error message: 

`[IMGUTILS @ 0x7fff59d4eab0] Picture size 0x0 is invalid`

I also attempted to use my YUV422p10le source as is and avoid converting my distorted videos to YUV420p, but ffmpeg returned this error: 

`Guessed Channel Layout for  Input Stream #0.1 : stereo
Incompatible pixel format 'yuv422p10le' for codec 'libx264', auto-selecting format 'yuv422p'`

I'm unsure the best way to address this issue. It seems that in order to get the color space of each video to match, I would need to transcode either the source or the distorted video again. This would likely result in inaccurate data. 

As a side note, I found this quote in the prores codec white paper: 

> All Apple ProRes 422 formats can support 4:2:0 or
>4:1:1 sources if the chroma is upsampled to 4:2:2 prior to encoding.

http://images.apple.com/final-cut-pro/docs/Apple_ProRes_White_Paper.pdf

**Comment by willfinnegan** [comment]
I did get the rawvideo, YUV420p source to work by specifying the frame size and frame rate before the input. I created 3, h264 distorted videos from that YUV420p source. However, when I ran vmaf on the distorted h264 files, it still resulted in an unusually low vmaf score of 1.3.

**Comment by li-zhi** [comment]
Is it possible to share the yuv files you have?

**Comment by willfinnegan** [comment]
@li-zhi The file size is quite large (300GB+)

**Comment by cosmin** [comment]
@willfinnegan the only thing VMAF will currently accept as input is raw YUV files. You can't pass it in H264 files, or Prores or anything else really. The problem is that when you run VMAF on any other file type, it won't know that the file you gave it is invalid, and it will happily read bytes as if it was an YUV video file. Therefore you'll get garbage results like scores of 1.3. 

The other indication that something has gone wrong should be that the frame count will most likely not be what you expect because the compressed video files won't be as large as a raw YUV file, and therefore there won't be enough bytes for the tool to happily churn through.

Your result of 1.4. from the yuv420p subsample of the reference video also seems suspicious and shouldn't be from subsampling differences alone. Or at least I would be shocked if that was the case. You converted the source to raw yuv420p, but did you convert your encoded files stored to raw YUV format as well before running the comparison? With a score of 1.4 I'm guessing you compared the raw reference video against H264 or similar encoded files, and that's why the score was so low.

The alternative explanation is that your reference and encoded files don't have the same resolution, which would also cause problems. An easy way to verify that you are running VMAF correctly is to check that the reference and encoded raw YUV files have the exact same file size. (Perhaps VMAF should add this sanity check itself to avoid issues from files having different resolutions, not being RAW, not having the same pixel format, etc).

Now that you have the source in raw YUV420p format, you should take the encoded H264 files that you created, and dump them to raw YUV420p format as well. Verify that the file size is the same, and run VMAF on that. If the encodes are any good you should get scores in the very high double digit range.

**Comment by willfinnegan** [comment]
@cosmin Thanks for the information!

**Comment by Ghayas-cyber** [comment]
I am using Y4M videos. Can I calculate VMAF for two Y4M videos

**Comment by li-zhi** [comment]
@Ghayas-cyber yes you can. Refer to https://github.com/Netflix/vmaf/tree/master/libvmaf/tools
