### ISSUE TITLE
where can I get a detailed paper about how to train and add 4K  10bit model for vmaf

### ISSUE THREAD

**Issue by Chamuel08** [Netflix/vmaf#496]
Hi, everyone, I want to know about how to train and add 4K 10bit model for vmaf in detail. But I can't find a detailed paper about the whole processing. So,  is there anyone who can show the detailed protocol about the training, and how to add model to the software?

**Comment by christosbampis** [comment]
Hi,
In order to train your own 4K 10bit model, you would need to create a dataset with such videos, carry out subjective experiment(s) to collect subjective data - ground truth data and then train the model. There is a lot of literature with prior research on some best practices when carrying out such experiments. There are also several ITU standards that you can look at (like the BT500 and later ones as well). If you have the data and extracted the features, you can train your model using the run_vmaf_training.py script provided as part of this repo.
