### ISSUE TITLE
input file with B frames  for libvmaf with ffmpeg sometimes will lead to a very low vmaf_score 

### ISSUE THREAD

**Issue by ROYduan** [Netflix/vmaf#587]

**Comment by 1480c1** [comment]
Are you asking if ffmpeg can handle sending b-frames to libvmaf?

**Comment by ROYduan** [comment]
when I transcode an mp4 file to flv file , and i put both to libvmaf with  ffmpeg ,it  caculated out an very slow vmaf score .
but when i first decode out both file to yuv, then put the yuv file to libvmaf with ffmpeg ,i get an very high vmaf score.

**Comment by ROYduan** [comment]
i think, there will an problem for ffmpeg to send frames to libvmaf   in timebase and pts ，thouht use this command，i couldn't get right vmaf score
./ffmpeg -y  -i 1.flv -i ref.mp4 -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=psnr=1:log_fmt=json:log_path=temp.log" -vframes 400  -f null -

**Comment by 1480c1** [comment]
Just making sure, can you paste your `ffmpeg` commands here? You can block them off using backticks \` to make sure they do not get mangled

I personally know that sometimes leaving it up to ffmpeg to decode and pass to filters sometimes might not produce the expected result (I previously tried comparing a lossless ffv1 to the original lossless y4m file using the `ssim` filter, but did not get 1 until I first converted the ffv1 to y4m and then compared)

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by ROYduan** [comment]
finally，I got an right vmaf score by fix fps for flv 
./ffmpeg_g -i 1.flv -i new10m.mp4 -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS,fps=25[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=psnr=1:log_fmt=json:log_path=tem.log" -vframes 400  -f null -

**Comment by LPFchan** [comment]
Hi, I've ended up in this thread because my vmaf scores after seeking (ffmpeg -ss) them was just terrible, and just wanted to add my little observation.

When trimming the video to sample and test, use the [slow seeking method](https://trac.ffmpeg.org/wiki/Seeking#Cuttingsmallsections) referenced in the ffmpeg wiki. 
`ffmpeg -i video.mp4 -ss 00:01:00 -to 00:02:00 -c copy cut.mp4`
Putting `-ss` before input was the culprit of skewed scores for me.
I've added `-avoid_negative_ts make_zero` to just make sure you're giving it the right treatment.

Here's my final code:
`ffmpeg -i (input) -ss 00:30 -vframes 360 -avoid_negative_ts make_zero -c copy ${filename%.*}tmp.mkv`
