### ISSUE TITLE
How to set a custom install folder?

### ISSUE THREAD

**Issue by mliradelc** [Netflix/vmaf#604]
I make a custom ffmpeg with static libraries. it would be great to put the header files from the compilation in my custom folder. But this not use a .configure file for this task.

How I can make this without modify the makefile itself???

**Comment by 1480c1** [comment]
if you are running the meson commands directly, you can add `--prefix /home/ccom1/.local/` or wherever you want to set the prefix, this will affect the paths meson will use when generating pkg-config files etc. To change where `ninja install` puts the files, rather than the prefix, you can use the `DESTDIR` environment variable, `DESTDIR=$PWD/build-ffmpeg-64-bit ninja -C build install`


https://mesonbuild.com/Running-Meson.html#installing
