### ISSUE TITLE
Did the HDR model ever get released?

### ISSUE THREAD

**Issue by hjmallon** [Netflix/vmaf#645]
I was just reading the presentation https://github.com/Netflix/vmaf/blob/master/resource/doc/VQEG_SAM_2018_025_VMAF_4K.pdf

It says that there will soon be a 'new HDR model'. It makes sense to me that this model would behave a little differently to the 4K/HD models. Was it ever released? It is not mentioned here https://github.com/Netflix/vmaf/blob/master/resource/doc/models.md.

**Comment by li-zhi** [comment]
The HDR model is still under development. We currently do not have a timeline for when it is going to be open sourced.

**Comment by hjmallon** [comment]
Thanks for clarifying @li-zhi , feel free to close this issue.

**Comment by Felixkruemel** [comment]
Is there any news regarding a HDR model?

**Comment by kedartatwawadi** [comment]
@li-zhi -> what happens currently when I run `vmaf -r hdr_src.y4m -d hdr_reconst.y4m` (`hdr_src` is a 10bit/16bit YUV420 input for example. As there is no "HDR" model, is the HDR input converted to SDR before running vmaf scores?

**Comment by venomone** [comment]
Any Update ???

**Comment by ShortyCM** [comment]
Google vmaf hdr and the first hit, for me anyway, is a Fraunhofer paper talking about using machine learning to predict VMAF HDR scores.  At least somebody is doing something, hehe.

**Comment by venomone** [comment]
Or even much simpler solution, at least this is how i do it for HLS processing.

Create an SDR Copy of the input source of about 10-20 Seconds and use the VMAF score from this at your actual HDR processing. Works like a charm boyz.

**Comment by ShortyCM** [comment]
Sorry, but I really doubt many people would find a sample of 10-20 seconds to be useful.  Things typically change too much and too often for such a small sample to be helpful.  I've done tests where I do a binary search encode job for every single GOP to hit a target score, and you wouldn't believe how much variance there is from GOP to GOP.  Since then I've had a hard time even using a single VMAF score from an entire video and trusting it to tell me anything.  Make a line graph of the VMAF scores for every frame from any random movie and examine it.  It's all over the place.  A mean score of 93 is quite far from 93 very often throughout the entire thing.  Encoding 10 seconds and saying "Yeah, CRF 24 will do for the whole movie." just isn't realistic if you actually care about the quality of the whole thing.

**Comment by venomone** [comment]
@ShortyCM 
You seem to be misunderstanding the core principle of my approach. If you're scrutinizing the entire video to pinpoint the optimal CRF value for encoding, that's an inefficient method, consuming excessive computing hours.

Consider a 20-minute video. The goal is to ascertain the best CRF using VMAF for the final encode. Typically, this would involve a full video analysis, demanding many hours. My method is remarkably quicker, about 100 times faster, for determining the CRF with VMAF. Here's the process, assuming the source is a HEVC mp4 file, inclusive of HDR10 and HDR10+ metadata.

Initially, I create a 'first-pass.log' file using ffmpeg. In Python, the command might be:

```
command = f'{options.get("path_ffmpeg")} -i "{job_reference["config"]["input"]}" -map 0:0 -c:v libx264 -preset ultrafast -crf 0 -an -sn -passlogfile "{motion_vectors_path}" -f null -y -pass 1 /dev/null'
```

This generates a log detailing the motion vectors ("mv") for each frame. A higher mv value indicates more motion in that frame. The key step is identifying the video segment with the highest motion by analyzing the log. Suppose it's between 00:10:05 and 00:10:22. This segment is most prone to pixelation during transcoding. We then apply VMAF comparison to this scene using a binary search algorithm.

The workflow is as follows:

1. Input.mp4 -> Generate 'first-pass.log'.
2. Analyze the log to locate the highest motion scene.
3. Create a reference.mp4 for that scene (00:10:05 - 00:10:22, -crf 0).
4. Generate distorted versions using a binary search.
5. Compare VMAF scores for different CRFs in the distorted versions.
6. Select the CRF matching your desired VMAF score.

This bypasses the need to analyze the entire video.

Regarding HDR: I've found VMAF doesn't necessarily require HDR analysis. For HDR10/HDR10+ inputs where HDR metadata retention is needed, I transcode only the high-motion scene to SDR for VMAF analysis, then apply the chosen CRF to the final HDR transcoding. This is particularly relevant for HLS streaming, where an SDR version is essential.

My experience with this method over thousands of videos assures:

1. The output file size remains minimal, akin to a full-clip VMAF analysis.
2. The VMAF analysis duration is drastically reduced.
3. Pixelation is eliminated across all scenes, as the analysis targets the most complex scene.

Transcoding a 20-minute video and conducting VMAF analysis as described typically takes about 35 minutes, yielding multiple versions (4K+HDR, 4K, 1080p, 720p, 360p) on a CPU-only setup (AMD Ryzen 7000 series).

It's worth noting that for VMAF, the difference between HDR and SDR is marginal, primarily involving metadata and pixel format, with the latter being more critical. The key in VMAF analysis is to avoid pixelation, and an SDR-based approach suffices for this. You can test this by encoding from HDR to SDR at a CRF that begins to show pixelation, then do the same from HDR to HDR while retaining metadata. You'll find the pixelation patterns similar in both processes, validating that HDR specifics are not vital for VMAF analysis or encoding compression settings.

Hope this clarifies and streamlines your encoding process.

**Comment by ShortyCM** [comment]
"You seem to be misunderstanding the core principle of my approach."  You said one vague sentence that had practically nothing to do with your approach.  Literally every single person that will ever read that sentence will obviously misunderstand your approach because you said practically nothing about your approach.  Your second post should've been your first, heh.  You're acting like your first post contained just as much to understand as your second post did.  It did not. Haha.  But thank you for expanding.

**Comment by venomone** [comment]
OKay, okay... Maybe I was a bit on the fast track here at my first one ^^, true.

**Comment by rsmvdl** [comment]
@hjmallon No i Dont think you are, it's almost 3 years ago Netflix announced HDR VMAF models, and still, nothing ...
