### ISSUE TITLE
RMSE calculation during training and testing

### ISSUE THREAD

**Issue by archanaveluswamy** [Netflix/vmaf#647]
Hi,

I am using run_vmaf_training.py and run_testing.py scripts to train our own model, the results of both gives me a PCC, SRCC and RMSE for the MOS and Predicted values and also a plot of the same values. What I found was before RMSE calculations the predicted scores are pre processed to do a sigmoid_adjust() in perf_metric.py. I assume this is done as per BT 500 document. 

While the RMSE is calculated on the predicted scores after sigmoid adjust, the plots generated after this still has the original predicted vmaf scores. Anyone know why this is done this way. What is the VMAF score we should be using.

Thanks,
Archana

**Comment by li-zhi** [comment]
The sigmoid_adjust is useful only for the purpose of reporting the PLCC, SROCC, RMSE scores. In a VMAF model, since the SVM fusion plays a similar role as the sigmoid_adjust (but only better), it is less needed. For other metrics like PSNR which doesn't have the fit, it is going to make the results more fair for them.
