### ISSUE TITLE
Very low VMAF scores for frames that doesn't look bad visually

### ISSUE THREAD

**Issue by hemrajchauhan** [Netflix/vmaf#699]
I converted a 4K video (http://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/tearsofsteel_4k.mov) from AVC to HEVC using Handbrake.
I ran VMAF for first 500 frames using ffmpeg.

ffmpeg.exe -ss 0 -i tearofsteel_4k_hevc.mkv -ss 0 -i tearsofsteel_4k.mov -frames:v 500 -lavfi "[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=model_path=Y\\:/FFmpeg_libvmaf/ffmpeg_libvmaf/share/model/vmaf_4k_v0.6.1.pkl:log_fmt=xml:log_path=Y\\:/FFmpeg_libvmaf/Samples/Source/tearofsteel_4k_hevc_vmaf_log.xml:psnr=1:ssim=1" -f null -

I am getting very low scores (<30) for some of the frames so i extracted that frames and found that visually it doesn't look bad.
I have attached few examples of the frames of the distorted video.
I have also attached the logs for vmaf, ffmpeg also containing stream info.
What could be a reason for low VMAF scores? Are there any limitations to VMAF for some content?

Frame_260_VMAF_24
![tearofsteel_4k_hevcFrame_260_VMAF_23](https://user-images.githubusercontent.com/44644640/98121681-e715ae80-1eaf-11eb-9582-b8ee36b0cffd.png)
Frame_311_VMAF_8
![tearofsteel_4k_hevcFrame_311_VMAF_8](https://user-images.githubusercontent.com/44644640/98121707-ee3cbc80-1eaf-11eb-9238-5f674ef0fe9a.png)
Frame_320_VMAF_14
![tearofsteel_4k_hevcFrame_320_VMAF_13](https://user-images.githubusercontent.com/44644640/98121728-f4329d80-1eaf-11eb-80fa-6cda1614e787.png)
Frame_323_VMAF_8
![tearofsteel_4k_hevcFrame_323_VMAF_8](https://user-images.githubusercontent.com/44644640/98121748-fbf24200-1eaf-11eb-9e3d-b05742e56472.png)

[tearofsteel_4k_hevc_vmaf_log.xml.xlsx](https://github.com/Netflix/vmaf/files/5488207/tearofsteel_4k_hevc_vmaf_log.xml.xlsx)
[tearofsteel_4k_hevc_ffmpeg_log.txt](https://github.com/Netflix/vmaf/files/5488210/tearofsteel_4k_hevc_ffmpeg_log.txt)

**Comment by li-zhi** [comment]
Thanks for reporting. Could you please submit this example following instructions here:
https://github.com/Netflix/vmaf#report-of-vmaf-bad-cases

**Comment by hemrajchauhan** [comment]
@li-zhi I tried several times (7-10) reporting the issue in Google form in the link above but whenever i press submit button, i get an error that "Something went wrong"

**Comment by li-zhi** [comment]
Hi I took a quick look at your xlsx file. My suspicion is that you have a frame sync issue. For a frame with low VMAF scores (for example, 18.5653) you also have a very low PSNR scores (for example, 18.4063). This signals that you haven't achieved perfect frame alignment.

I know `-ss` in FFmpeg is not frame-accurate. Not sure if that is the root cause.

**Comment by hemrajchauhan** [comment]
@li-zhi Sorry for the late reply. I can confirm that without -ss 0 in the cmd line, the results are still the same.

**Comment by krasuluk** [comment]
The above issue seems to be due to a misalignment of frames between the reference and the distorted version. Looking at the motion feature, it seems there are some duplicated frames and every third frame has low PSNR and other feature values. 

@thomaswilliams123 - is it possible something similar is happening in your case?

**Comment by nilfm99** [comment]
Closing as inactive
