### ISSUE TITLE
Resolution, display height and quality metric

### ISSUE THREAD

**Issue by nandakd** [Netflix/vmaf#74]
Hello!
I read the FAQ note describing why a 480p video has much higher VMAF scores. What you're saying is VMAF treats the 1080p display at 3H viewing distance as the standard for computing a quality score. Assuming display size directly proportional to display resolution, if we now use a 480p display, the quality scores should be computed with a viewing distance that is closer, not farther away, but preserving the same 3H ratio (i.e. 3 * 480/1080 = 1.33H). This is reflective of the fact that as screen sizes get smaller, we need to sit closer, not farther away.  

Completely agreed with what is described in the two bullet points.

**Comment by mht13** [comment]
But shouldn't the approach be to just take into account the viewing distance as opposed to the two suggestions of upscaling, which is in fact later mentioned that it can lead to inaccurate results since the model was not tested for upscaled files?.

Incidentally, why a distance of 3H? I understand that a number has to be used consistently in the perceptual tests to train the model but any particular reason why not, say, 2H, or 4H? As far as I understand the ITU recommendations (P.910) are anywhere between 1 and 8H, leaving up to the case under study.

**Comment by JohnhqWang** [comment]
Hi guys,

Given that a video was displayed without scaling and the distance of two displayed is a constant for different monitors, the optimal viewing distance is fixed **regardless** of its native resolution, i.e. no matter it's 1080p or 480p. The reason could be found at [ITU-R BT 2022](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2022-0-201208-I!!PDF-E.pdf), section 1.3.2

> The design viewing distance (DVD), or optimal viewing distance, for a digital system is the
> distance at which two adjacent pixels subtend an angle of 1 arc-min at the viewer’s eye

Table 1 also answers why the distance was set as 3H for 1080p videos.

Upscaling artifacts came in when 480p videos were upscaled to 1080p during subjective test, of course with the same viewing distance as 1080p (3.2H, or 3H). So quality under this scenario is different from that without upscaling artifacts.

**Comment by mht13** [comment]
I am quite confused about what was exactly used for training the VMAF as provided by default. 

On one hand, there are those two suggestions in the FAQ to upscale, which I would agree that should give different qualities as mentioned in the above post. On the other hand the above post mentions that artifacts *came in* when 480p were upscaled. So while the answer in the FAQ suggests upscaling, the one above indicates that doing so would not give "accurate" results. 

Does "artifacts came in" refer to the tests actually used to build train VMAF as provided? 

If not, and I am even more confused, the original blog (http://techblog.netflix.com/2016/06/toward-practical-perceptual-video.html) says

"Using the source clips, we encoded H.264/AVC video streams at resolutions ranging from 384x288 to 1920x1080 (....) We then ran subjective tests (...)."

John, where/are you part of the project and if so can you and clarify this with Li Zhi (who apparently posted the FAQ)? There seem to be conflicting points of view. 

So, to iterate on the question: what should one expect from applying native resolutions that are not 1080p? What resolutions were used to train the metric as provided by default? 

Part of the confusion, at least from my side, is that after a while the following article was posted on the main GitHub documentation as main reference: https://arxiv.org/abs/1611.01715. But that paper does not actually explain the details of what is summarized in the aforementioned tech blog or the discussion of this thread. 

In fact, I was surprised when I saw a git push with a new "add-on" for cell phones. As JohnhqWang mentions, the resolution should be irrelevant provided the viewing distance is the same, so I am not sure what exactly it is meant by a model for cell phones. I guess by looking at the code one could decipher that, but if this is meant to be an open source project, should it have some more detailed technical documentation? 

Thanks so much

**Comment by yuhjay** [comment]
Hi mht13,

VMAF is designed for simulating how people perceive video quality when watching it on TVs/mobile devices. You will not change your monitor size because your player will upscale your video to fit your monitor size. Thus, resolution is irrelevant. You may want to check what is "adaptive streaming". Assuming the mezzanines are perfect, compression and upscaling are two main artifacts will be added during the transcoding, decoding and displaying. To build the nonlinear model, subjective testing is necessary to collect human opinions. If you read ITU stuff about subjective testing, you will know what is behind the algorithm. The different models are based on the different settings of subjective tests (TV or mobile device).

Joe

**Comment by nandakd** [comment]
Joe - thanks. This sentence from the FAQ is specifically confusing.

> VMAF is modeling the viewing distance of 3H = 6.75H’. In other words, if you calculate VMAF on the 480 resolution video pair, you are going to predict the perceptual quality of viewing distance 6.75 times its height.

This seems wrong - for a 480 resolution video pair, VMAF should certainly not be assigning higher quality scores. Instead, bullet point #2 in the FAQ is the only methodology - upsample both reference/distorted to 1080p, which is the display resolution. Yes, this means that the reference is no longer pristine and interpolation artifacts have been introduced.

**Comment by yuhjay** [comment]
Hi nandakd,

Not exactly. The FAQ you quoted seems fine to me. The intention of bullet#1 is to describe an exceptional case for its model. Either you upscale both to 1080P or you may see strange numbers. I guess this is what Zhi want to explain.

Joe

**Comment by JohnhqWang** [comment]
Hi mht13,

I am not in this project but I happen to know the viewing distance issue.  

1. First, let's clarify that H (1080p) and H' (480p) refer to **active picture height**, not monitor height. The recommended viewing distance for them are ~3H and 7H, respectively. Actually, 3*H(1080) = 6.75*H'(480) and it comply with ITU 2022, so the quoted bullet is fine @nandakd . 

2. Second, according to the FAQ, the implicit assumption VMAF is it models the viewing distance of 1080 resolution. Videos in lower resolution would be upscaled to 1080p.

3. video quality is application specific. The conclusions are different between a scenario w/o scaling (pure compression artifacts) with one w/ scaling (compression + interpolation). Similarly, it is quite different to view it on TV or mobile device. Netflix does what they are more interested in, i.e. the setting w/ scaling.

Then, what would one expect to apply VMAF on 480p videos? Following the approaches suggested in FAQ. 

Bullet 1, 1080p reference  + distorted clip upscale from 480p to 1080p, the quality score would not be high as it's the case VMAF tries to model. 

Bullet 2, upscale both to 1080p, then there is no surprise the quality score might be high. VMAF is a full-reference metric, and the upscaled reference is no longer pristine.

**Comment by mht13** [comment]
Guys, thanks so much! This makes perfect sense to me now. 

I was unaware that the intent was to use the full screen (of either a TV or a mobile) and then I guess it is natural to assume that the TV is 1080p these days (or 4k) and then the need to upscale. I was thinking that perhaps the metric had been trained using displays showing native resolution (say, if I stream 480p on a computer screen under a very low connection, I might not want to upscale and see many artifacts but instead watch at native resolution). 

Thanks again, especially @JohnhqWang !

**Comment by li-zhi** [comment]
@JohnhqWang @yuhjay Thanks for chiming in with the clarification. I just wanted to add a few more points.

@mht13 : regarding the Arxiv paper, please do not consider it as a main reference of VMAF. It is only to address one specific aspect, which is how to extract high-quality subjective scores to be used for VMAF training. Instead, the blogpost should be the main reference. 

Perhaps what I missed in the blogpost was: after a high-resolution source (which we assumed  available) was encoded in different resolutions, how they were displayed to the viewers during subjective testing. This should be clear for a Netflix viewer -- the pictures are always upscaled to full screen. With this, I hope the rest all makes sense.

Regarding the TV vs. phone model, there are a number of factors that could contribute to the differences - viewing distance, screen size, and psychological factor (viewers would expect less on a phone device). Since the models are data-driven, they should have encompassed all of these factors.

@nandakd : the sentence that you quoted was trying to give an interpretation of the scores obtained by directly computing VMAF scores at native 480 resolution. It shouldn't be interpreted as right thing to do -- it all depends on your specific need. Again let me summarize the three scenarios and their interpretations:

a) Calculate VMAF on a 480 encode w.r.t. its 1080 source, by upscaling the 480 encode to 1080 first: this is most correct thing to do. The resulting score is a prediction of quality when viewing the upscaled video from 3H.

b) Calculating VMAF on a 480 encode w.r.t. its 480 source: the resulting score is a prediction of quality when viewing the video from 6.75H (same physical distance as a), but without upscaling, the picture is displayed smaller).

c) Calculating VMAF on a 480 encode w.r.t. its 480 source, both upscaled to 1080 first: the resulting score may be higher than a), since the prediction fails to account for the upscaling artifacts presented in the non-pristine source.

**Comment by nandakd** [comment]
@li-zhi: Thanks - that makes it clear. Can you confirm that the publicly available Netflix ref-dist pairs and subjective scores were evaluated using scenario a) ?

**Comment by mht13** [comment]
Thanks @li-zhi  for all the extra clarifications. 

The blogpost cannot be really used as a technical report, though, it is very high level and lacks details. Can we expect some tech report, paper or preprint at some point? It would have preempted all these questions, for example. 

The assumption that viewers always upscale to a full 1080p screen seems like a strong one to me. 

Are there numbers (percentage of viewers and their displays) about this? I know people who watch netflix on their laptops, which are not necessarily 1080p, and people who own 720p TVs. Especially in foreign countries. As well as people who use 4k displays. 

One could say, well, we are targeting at 1080p TVs, but that was not clear to me from the  blogpost. 

Thanks!

**Comment by mohamad1374131** [comment]
hi. i have a question about VMAF score.
is that different between VMAF score for a video with 480p and 1080p?
note that there is a single video but with different resolution.
please answer to me.

**Comment by li-zhi** [comment]
@mohamad1374131 please refer to this question regarding VMAF and resolutions: https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-when-computing-vmaf-on-low-resolution-videos-480-pixel-height-for-example-why-the-scores-look-so-high-even-when-there-are-visible-artifacts

You may also find some best practice tips in the second tech blog at: https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12
