### ISSUE TITLE
VMAF output range across several bitrates

### ISSUE THREAD

**Issue by madcityrn** [Netflix/vmaf#87]
We're attempting to compare VMAF's result across multiple bitrate encodes for a single asset. The original asset is a 29.97fps, 1080 MPEG-2 file and close to CBR (13.5 mbps average bitrate). We first transcode it to an MP4 lossless "reference" using Handbrake. The resultant file is VBR, 720, 24fps, and with an average bitrate of 17.5 mbps. We then use Handbrake to transcode the reference file to 720, 24fps versions from 1 -> 17 mbps. Lastly we use VMAF to grade these assets against the MP4 reference we created using the following command:

./run_vmaf yuv420p 1280 720 [source] [compare target] --out-fmt json

Here is a table of the results we obtained:

avg, mbps    vmaf
1		18.9453
2		19.2293
3		19.3395
4		19.3839
5		19.4464
6		19.4368
7		19.4528
8		19.4759
9		19.4794
10		19.4921
11		19.4942
12		19.5033
13		19.5175
14		19.5053
15		19.515
16		19.5202
17		19.5212
reference		99.9911

We had expected to see results in the 20s from 1->3 mbps, with values scaling up towards 99 as bitrate increased. File size and visual inspection would indicate more of a change in encoded quality than VMAF is indicating.

Any suggestions on what we're doing wrong, or where our process is incorrect?

One last thing to mention: the length of the asset is 4316 frames, or ~3 minutes. Wanted to mention this in case there is an issue with VMAF and relatively short video lengths compared to your use case.

**Comment by li-zhi** [comment]
Hi,

Looks like you are running VMAF on the compressed bitstream, instead of on the raw YUV stream. Two ways you can correct this:
1) decode .mp4 file into YUV (e.g. yuv420p) format and then run VMAF on the raw file.
2) use ffmpeg2vmaf instead of run_vmaf. This allows directly using non-YUV video inputs to VMAF.

By the way, the fact that the original video and the encoded video having different FPS will make the videos out of sync. You should be using the same FPS.
