### ISSUE TITLE
Errors in readme for python installation 

### ISSUE THREAD

**Issue by JoshuaEbenezer** [Netflix/vmaf#886]
There is an error in the python readme for VMAF installation (https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md). 

 `sudo [package-manager] install nasm ninja doxygen` does not work for Ubuntu 20.04 because ninja is not a package for the distribution. `pip install meson ` should install ninja by itself.

**Comment by slhck** [comment]
Hm, this guide has changed significantly since I last saw it.

I think it would be even easier to give separate instructions for different types of distributions such as Debian-based ones, macOS, etc. I prefer it when you can directly copy-paste instructions without having to replace elements of the command.

I proposed a fix here: https://github.com/Netflix/vmaf/pull/887

**Comment by JoshuaEbenezer** [comment]
Absolutely.. #887 looks like a good fix for this

**Comment by li-zhi** [comment]
I merged #887. Thanks for the PR @slhck !
