### ISSUE TITLE
Score Range

### ISSUE THREAD

**Issue by zuo-chao** [Netflix/vmaf#979]
I want to know the range of scores for vmaf and other subitems. 
I just know that VMAF is 0-100, ssim is 0-1. But the vif score it greater than 1, I'm confused.
vmaf   0-100
ssim 
ms_ssim
psnr
integer_adm2
integer_adm_scale0
integer_adm_scale1
integer_adm_scale2
integer_adm_scale3
integer_vif_scale0
integer_vif_scale1
integer_vif_scale2
integer_vif_scale3

**Comment by nilfm** [comment]
Hi, sorry for the super late reply. I'll still leave the answers here in case anyone is looking for this info.

* VMAF is indeed bounded between [0, 100], because of the score clip specified in the models: [example](https://github.com/Netflix/vmaf/blob/master/model/vmaf_4k_v0.6.1.json#L16-L17).
* SSIM is bounded between [-1, 1]. Here's an [article](https://ece.uwaterloo.ca/~z70wang/publications/TIP_SSIM_MathProperties.pdf) with some mathematical properties. Same for MS-SSIM.
* PSNR theoretically can go from [0, infinity). However, the libvmaf implementation bounds it depending on bit depth, see [here](https://github.com/Netflix/vmaf/blob/master/libvmaf/src/feature/float_psnr.c#L49-L60). Other implementations, such as `ffmpeg`, do not cap.
* ADM and VIF (and their sub-features) are capped from below at 0, but can exceed 1, see a test case for ADM [here](https://github.com/Netflix/vmaf/blob/master/python/test/vmafexec_feature_extractor_test.py#L426) and for VIF [here](https://github.com/Netflix/vmaf/blob/master/python/test/vmafexec_feature_extractor_test.py#L479C10-L479C10).

@christosbampis feel free to correct me or add anything else here
